config/routes.rb
Horoscope::Application.routes.draw do
  
  resources :in_app_purchases

  resources :user_lexicons, except: [:new, :create] do
    collection do
      post :pub_unpub_user_lexicon
    end
  end

  resources :videos do
    collection do
      post :pub_unpub_video
    end
  end

  resources :information_pages  
  match "info/:name" => 'information_page_viewer#show', :as => :view_page
  
  resources :seasons

  resources :astro_extras do
  	collection do
  		post :pub_unpub_astro_extra
  		match :zodiac_names
  	end
  end







  namespace :api do
    get "user_lexicon/answers" => "user_lexicons#answers"
    post "user_lexicon/question" => "user_lexicons#create_user_lexicon"
    match "/videos" => "videos#get_videos"
    match "/time" => "server_times#get_server_time"
    match "/astro_extra" => "astro_extras#index"
  	resources :horoscopes
  	match "/token" => "genrate_token#token"
    get "/info" => "info_pages#info"
  	resources :validations do
  		collection do
  			post :iap
  			post :voucher
  		end
  	end
  end

  devise_for :users
  resources :users 
  resources :horoscope_dailies do
  	collection do
  		post :publish_unpub_horoscope
  		match :zodiac_names
  	end
  end
  resources :horoscope_monthlies do
    collection do
  		post :publish_unpub_horoscope
      match :zodiac_names
  	end
  end  
  resources :horoscope_weeklies do
    collection do
  		post :publish_unpub_horoscope      
      match :zodiac_names
  	end
  end
  resources :vouchers do
  	collection do
  		post :pub_unpub_voucher
  	end
  end
  authenticated :user do
  	root :to => 'home#index'
  end
  root :to => "home#index"

  
  










end

app/models/season.rb
class Season < ActiveRecord::Base

	has_many :astro_extras

  attr_accessible :name, :date_from, :date_to, :year

  before_validation :add_year

  # SEASON_NAME = ["Spring", "Winter", "Autumn", "Summer"]
  
  validates :date_from, :date_to, overlap: {:message_title => "Duration", :message_content => "can't be overlap with other season."}
  validates :date_from, presence: {message: "can't be blank"}
  validates :date_to, presence: {message: "can't be blank"}
  validates :name, presence: {message: "can't be blank"}, 
  	uniqueness: { scope: :year, message: " of season must be unique for a year."}
  
  validate :season_period

  def season_period
  	if date_from.present? and date_to.present? and (date_from.to_date > date_to.to_date)
  		errors.add(:date_from, "should be less than date_to")
  		return false
  	end
  end

  def add_year
  	self.year = self.date_from.to_date.year.to_s if self.date_from.present?
  end

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  
  def index
    @seasons = Season.all
  end

  def show
    @season = Season.find(params[:id])
  end

  def new
    @season = Season.new
  end

  def edit
    @season = Season.find(params[:id])
  end

  def create
    @season = Season.new(params[:season])

    respond_to do |format|
      if @season.save
        format.html { redirect_to seasons_path, notice: 'Season was successfully created.' }
        format.json { render json: @season, status: :created, location: @season }
      else
        format.html { render action: "new" }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @season = Season.find(params[:id])

    respond_to do |format|
      if @season.update_attributes(params[:season])
        format.html { redirect_to seasons_path, notice: 'Season was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @season = Season.find(params[:id])
    @season.destroy

    respond_to do |format|
      format.html { redirect_to seasons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.haml
= form_for @season do |f|
  - if @season.errors.any?
    #error_explanation
      %h2= "#{pluralize(@season.errors.count, "error")} prohibited this season from being saved:"
      %ul
        - @season.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    / # = f.select :name, ( Season::SEASON_NAME)
    = f.text_field :name
  .field
    = f.label :date_from
    = f.text_field  :date_from
  .field
    = f.label :date_to
    = f.text_field  :date_to 
  .actions
    = f.submit 'Save'

app/views/seasons/edit.html.haml
%h1 Editing season

= render 'form'

= link_to 'Show', @season
\|
= link_to 'Back', seasons_path

app/views/seasons/index.html.haml
%h1 Listing seasons

%table
  %tr
    %th Name
    %th Date from
    %th Date to
    %th
    %th
    %th

  - @seasons.each do |season|
    %tr
      %td= season.name
      %td= season.date_from
      %td= season.date_to
      %td= link_to 'Show', season
      %td= link_to 'Edit', edit_season_path(season)
      %td= link_to 'Destroy', season, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Season', new_season_path

app/views/seasons/new.html.haml
%h1 New season

= render 'form'

= link_to 'Back', seasons_path

app/views/seasons/show.html.haml
%p#notice= notice

%p
  %b Date from:
  = @season.date_from
%p
  %b Date to:
  = @season.date_to

= link_to 'Edit', edit_season_path(@season)
\|
= link_to 'Back', seasons_path