config/routes.rb
Horoscope::Application.routes.draw do
  
  resources :in_app_purchases

  resources :user_lexicons, except: [:new, :create] do
    collection do
      post :pub_unpub_user_lexicon
    end
  end

  resources :videos do
    collection do
      post :pub_unpub_video
    end
  end

  resources :information_pages  
  match "info/:name" => 'information_page_viewer#show', :as => :view_page
  
  resources :seasons

  resources :astro_extras do
  	collection do
  		post :pub_unpub_astro_extra
  		match :zodiac_names
  	end
  end







  namespace :api do
    get "user_lexicon/answers" => "user_lexicons#answers"
    post "user_lexicon/question" => "user_lexicons#create_user_lexicon"
    match "/videos" => "videos#get_videos"
    match "/time" => "server_times#get_server_time"
    match "/astro_extra" => "astro_extras#index"
  	resources :horoscopes
  	match "/token" => "genrate_token#token"
    get "/info" => "info_pages#info"
  	resources :validations do
  		collection do
  			post :iap
  			post :voucher
  		end
  	end
  end

  devise_for :users
  resources :users 
  resources :horoscope_dailies do
  	collection do
  		post :publish_unpub_horoscope
  		match :zodiac_names
  	end
  end
  resources :horoscope_monthlies do
    collection do
  		post :publish_unpub_horoscope
      match :zodiac_names
  	end
  end  
  resources :horoscope_weeklies do
    collection do
  		post :publish_unpub_horoscope      
      match :zodiac_names
  	end
  end
  resources :vouchers do
  	collection do
  		post :pub_unpub_voucher
  	end
  end
  authenticated :user do
  	root :to => 'home#index'
  end
  root :to => "home#index"

  
  










end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  validates :username, presence: true
  validates :username, uniqueness: true, if: -> { self.username.present? }
    # Include default devise modules. Others available are:
    # :token_authenticatable, :confirmable,
    # :lockable, :timeoutable and :omniauthable
    #devise :database_authenticatable, :registerable,
    #       :recoverable, :rememberable, :trackable, :validatable
    # attr_accessible :title, :body
  
    #devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
    devise :database_authenticatable,  :rememberable, :trackable, :validatable, :authentication_keys => [:login]
    #attr_accessible :title, :body
    attr_accessible :role_ids
    attr_accessible :role_ids,  :as => :admin
    #attr_accessible :registerable,  :as => :admin
    #attr_accessible :name, :email, :password, :password_confirmation, :remember_me
    attr_accessible  :username,:name, :email, :password, :password_confirmation, :remember_me
    attr_accessible :login
    attr_accessor :login

  
    def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end
    def email_required?
      false
    end

    def email_changed?
      false
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_filter :authenticate_user!

  def index
     authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
   authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    unless @user == current_user
       @user = User.find(params[:id])
     else
      redirect_to users_path, :notice => "Not authorized "
    end 
  end

  def new
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.new
  end

  def edit
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
     unless @user == current_user
       @user = User.find(params[:id])
     else
      redirect_to users_path, :notice => "Can't edit yourself."
    end 
  end

  def create
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.new(params[:user])
    if @user.save
      #redirect_to @user, :flash => { :success => 'User was successfully created.' }
      redirect_to users_path, :flash => { :success => 'User was successfully created.' }
    else
      render :action => 'new'
    end
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    
    if @user.update_attributes(params[:user])           
      redirect_to users_path, :notice => "User updated."      
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
     
  #  authorize! :update, @user, :message => 'Not authorized as an administrator.'
  #  @user = User.find(params[:id])

  #  if @user.update_attributes(params[:user])
   #   sign_in(@user, :bypass => true) if @user == current_user
  #    redirect_to @user, :flash => { :success => 'User was successfully updated.' }
  #  else
   #   render :action => 'edit'
  #  end
  end

  def destroy
     authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
  #  authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
  #  @user = User.find(params[:id])
  #  @user.destroy
   # redirect_to users_path, :flash => { :success => 'User was successfully deleted.' }
   #end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
%table.table.table-condensed.table-bordered 
  %tr
    %th Editor bearbeiten
  = form_for @user do |f|
    - if @user.errors.any?
      .error_explanation
        %h2
          = pluralize(@user.errors.count, "error")
          prohibited this user from being saved:
        %ul
          - @user.errors.full_messages.each do |msg|
            %li= msg
    %tr
      %td= f.label :email
      .controls
        %td= f.email_field :email , :autofocus => true ,:required => true
    %tr
      %td= f.label :username
      .controls
        %td= f.text_field :username, :required => true
    %tr
      %td= f.label :password
      .controls
        %td= f.password_field :password  , :autocomplete => "off", :hint => "leave it blank if you don't want to change it", :required => false 
    %tr
      %td= f.label :password_confirmation
      .controls
        %td= f.password_field :password_confirmation,:hint => "we need your current password to confirm your changes", :required => true
    %tr
      %td= f.submit :class => 'btn btn-primary' 
      %td= link_to "Cancel", users_path, :class => 'btn'

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/_user.html11.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/edit.html.haml
%h1 Edit User
= render 'form'

app/views/users/index.html.haml
%h1 Editors
.span8
  %table.table.table-condensed.table-bordered 
    %thead
      %tr
        %th Benutzer
        %th Email
        %th Registered
        %th Role
        %th Aktion
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td=  user.username
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a{:'data-toggle' => "modal", :href => "#role-options-#{user.id}"}change-role
            = render user  unless user == current_user       
          %td= link_to("#{image_tag('edit.png')}  bearbeiten".html_safe, edit_user_path(user)) unless user == current_user    
          %td= link_to("#{image_tag('delete.png')} löschen".html_safe, user_path(user), :data => { :confirm => "Sind Sie sicher?" }, :method => :delete) unless user == current_user  
  %tr 
    %td= link_to '+ Neuer Benutzer', new_user_path, :class => 'btn btn-info'

app/views/users/index.html1.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>      
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/index.html_old.haml
%h1 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Benutzer
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td=  user.username
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{:'data-toggle' => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role 
            = render user  unless user == current_user                      
          %td= link_to("bearbeiten", edit_user_path(user), :class => 'btn btn-mini') unless user == current_user    
          %td= link_to("löschen", user_path(user), :data => { :confirm => "Sind Sie sicher?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user  
  = link_to 'Neuer Benutzer', new_user_path

app/views/users/new.html.haml
%h1 New User
= render 'form'

app/views/users/show.html.haml
%h1 User
%p
  %strong Email:
  = @user.email
= link_to 'All Users', users_path
|
\#{link_to 'Edit User', edit_user_path(@user)} 
|
\#{link_to 'Delete User', user_path(@user), :method => 'delete', :confirm => 'Are you sure?'}

app/views/users/show_old.html_1.haml
/ !%h1 User
/ !%p
/ !  %strong Email:
/ !  = @user.email
/ != link_to 'All Users', users_path
/ !|
/ !\#{link_to 'Edit User', edit_user_path(@user)} 
/ !|
/ !\#{link_to 'Delete User', user_path(@user), :method => 'delete', :confirm => 'Are you sure?'}