config/routes.rb
Horoscope::Application.routes.draw do
  
  resources :in_app_purchases

  resources :user_lexicons, except: [:new, :create] do
    collection do
      post :pub_unpub_user_lexicon
    end
  end

  resources :videos do
    collection do
      post :pub_unpub_video
    end
  end

  resources :information_pages  
  match "info/:name" => 'information_page_viewer#show', :as => :view_page
  
  resources :seasons

  resources :astro_extras do
  	collection do
  		post :pub_unpub_astro_extra
  		match :zodiac_names
  	end
  end







  namespace :api do
    get "user_lexicon/answers" => "user_lexicons#answers"
    post "user_lexicon/question" => "user_lexicons#create_user_lexicon"
    match "/videos" => "videos#get_videos"
    match "/time" => "server_times#get_server_time"
    match "/astro_extra" => "astro_extras#index"
  	resources :horoscopes
  	match "/token" => "genrate_token#token"
    get "/info" => "info_pages#info"
  	resources :validations do
  		collection do
  			post :iap
  			post :voucher
  		end
  	end
  end

  devise_for :users
  resources :users 
  resources :horoscope_dailies do
  	collection do
  		post :publish_unpub_horoscope
  		match :zodiac_names
  	end
  end
  resources :horoscope_monthlies do
    collection do
  		post :publish_unpub_horoscope
      match :zodiac_names
  	end
  end  
  resources :horoscope_weeklies do
    collection do
  		post :publish_unpub_horoscope      
      match :zodiac_names
  	end
  end
  resources :vouchers do
  	collection do
  		post :pub_unpub_voucher
  	end
  end
  authenticated :user do
  	root :to => 'home#index'
  end
  root :to => "home#index"

  
  










end

app/models/video.rb
class UrlValidator < ActiveModel::EachValidator
 
  def validate_each(record, attribute, value)
    valid = begin
      URI.parse(value).kind_of?(URI::HTTP)
    rescue URI::InvalidURIError
      false
    end
    unless valid
      record.errors[attribute] << (options[:message] || "is an invalid URL")
    end
  end
 
end


class Video < ActiveRecord::Base
  attr_accessible :description, :is_active, :title, :url

  validates :url, presence: true, url: true
  validates :title, presence: {message: "can't be blank."}

  self.per_page = 10

  def as_json(options={})
    { video_url: self.url,
      title: self.title,
      description: self.description 
    }
  end

end

app/controllers/api/videos_controller.rb
class Api::VideosController < Api::BaseController

  before_filter :rest_of_horoscope_restrict_access

  respond_to :json

  def get_videos
  	respond_with Video.where(is_active: true)
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  
  def index
    get_videos
  end

  def show
    @video = Video.find(params[:id])
  end

  def new
    @video = Video.new
  end

  def edit
    @video = Video.find(params[:id])
  end

  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to videos_path, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to videos_path, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end

  # To publish video
  def pub_unpub_video
    
    uri = URI.parse(request.headers["Referer"])

    parameters = {:page => 1}
    parameters[:page] =  CGI.parse(uri.query)['page'].first if uri.query.present?
    params.merge!(parameters)


    video = Video.find(params[:id])
    video.update_attributes(is_active: params[:is_active] )   
    get_videos

    render :partial => 'videos'

  end

  private
  
  def get_videos
    @videos = Video.order('id').paginate(page: params[:page])
  end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.haml
%table.table.table-condensed.table-bordered 
  %tr
    %th Video bearbeiten
  = form_for @video do |f|
    - if @video.errors.any?
      #error_explanation
        %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
        %ul
          - @video.errors.full_messages.each do |msg|
            %li= msg
            
    %tr 
      %td= f.label :url
      %td= f.text_field :url
    %tr 
      %td= f.label :title
      %td= f.text_field :title
    %tr 
      %td= f.label :description
      %td= f.text_area :description, :rows => 3
    %tr 
      %td= f.label :is_active
      %td= f.check_box :is_active
    %tr 
      %td=f.submit 'Save',:class => 'btn btn-primary'
      %td= link_to "Cancel", videos_path,:class => 'btn'

app/views/videos/_videos.html.haml
%table.table.table-condensed.table-bordered 
  %tr
    %th
    %th Aktiv
    %th URL
    %th Titel
    %th Beschreibung
    %th Aktion
    %th

  - @videos.each do |video|
    %tr
      %td= check_box_tag "published_#{video.id}", video.id, video.is_active, :class => "pub_video"
      %td= (video.is_active) ? "published" : "unpublished"
      %td= video.url
      %td= video.title
      %td= video.description
      %td= link_to 'Edit', edit_video_path(video)
      %td= link_to 'Destroy', video, :method => :delete, :data => { :confirm => 'Are you sure?' }

:javascript
  $(function() {
    return $(".pub_video").on("change", function() {
      var id, publish;
      publish = $(this).is(":checked");
      id = $(this).val();
      return $.ajax({
        type: "POST",
        dataType: "html",
        url: "/videos/pub_unpub_video",
        data: {
          is_active: publish,
          id: id
        },
        success: function(data) {
          return $("#video_content").html(data);
        },
        error: function(object, error) {
          return console.log(error);
        }
      });
    });
  });

app/views/videos/edit.html.haml
%h1 Editing video

= render 'form'

= link_to 'Show', @video
\|
= link_to 'Back', videos_path

app/views/videos/index.html.haml
%h1 Videos
- if @videos.blank?
  = "No video available."
- else
  %div{:id => 'video_content'}
    = render "videos"

%br
= will_paginate

%br
= link_to '+ Neues Video', new_video_path, :class => 'btn btn-info'

app/views/videos/new.html.haml
%h1 New video

= render 'form'

= link_to 'Back', videos_path

app/views/videos/show.html.haml
%p#notice= notice

%p
  %b Url:
  = @video.url
%p
  %b Title:
  = @video.title
%p
  %b Description:
  = @video.description
%p
  %b Is active:
  = @video.is_active

= link_to 'Edit', edit_video_path(@video)
\|
= link_to 'Back', videos_path