config/routes.rb
Horoscope::Application.routes.draw do
  
  resources :in_app_purchases

  resources :user_lexicons, except: [:new, :create] do
    collection do
      post :pub_unpub_user_lexicon
    end
  end

  resources :videos do
    collection do
      post :pub_unpub_video
    end
  end

  resources :information_pages  
  match "info/:name" => 'information_page_viewer#show', :as => :view_page
  
  resources :seasons

  resources :astro_extras do
  	collection do
  		post :pub_unpub_astro_extra
  		match :zodiac_names
  	end
  end







  namespace :api do
    get "user_lexicon/answers" => "user_lexicons#answers"
    post "user_lexicon/question" => "user_lexicons#create_user_lexicon"
    match "/videos" => "videos#get_videos"
    match "/time" => "server_times#get_server_time"
    match "/astro_extra" => "astro_extras#index"
  	resources :horoscopes
  	match "/token" => "genrate_token#token"
    get "/info" => "info_pages#info"
  	resources :validations do
  		collection do
  			post :iap
  			post :voucher
  		end
  	end
  end

  devise_for :users
  resources :users 
  resources :horoscope_dailies do
  	collection do
  		post :publish_unpub_horoscope
  		match :zodiac_names
  	end
  end
  resources :horoscope_monthlies do
    collection do
  		post :publish_unpub_horoscope
      match :zodiac_names
  	end
  end  
  resources :horoscope_weeklies do
    collection do
  		post :publish_unpub_horoscope      
      match :zodiac_names
  	end
  end
  resources :vouchers do
  	collection do
  		post :pub_unpub_voucher
  	end
  end
  authenticated :user do
  	root :to => 'home#index'
  end
  root :to => "home#index"

  
  










end

app/models/voucher.rb
class Voucher < ActiveRecord::Base

  attr_accessible :name, :code, :is_active, :valid_days

  validates :code, uniqueness: true, presence: {message: "can't be blank."}, length: { minimum: 8 , maximum: 12, message: "should be in between 8 - 12." }
  
  validates :valid_days, presence: {message: "can't be blank."}, numericality: { greater_than_or_equal_to: 1, message: "must be greate or equal to 1." }
  validates :is_active, presence: true, :if => 'is_active.nil?'

  self.per_page = 10

end

app/controllers/vouchers_controller.rb
class VouchersController < ApplicationController	
  
  def index
    get_vouchers
  end

  def show
    @voucher = Voucher.find(params[:id])
  end

  def new
    @voucher = Voucher.new
  end

  def edit
    @voucher = Voucher.find(params[:id])
  end

  def create
    @voucher = Voucher.new(params[:voucher])

    respond_to do |format|
      if @voucher.save
        format.html { redirect_to @voucher, notice: 'Voucher was successfully created.' }
        format.json { render json: @voucher, status: :created, location: @voucher }
      else
        format.html { render action: "new" }
        format.json { render json: @voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @voucher = Voucher.find(params[:id])

    respond_to do |format|
      if @voucher.update_attributes(params[:voucher])
        format.html { redirect_to @voucher, notice: 'Voucher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @voucher = Voucher.find(params[:id])
    @voucher.destroy
    flash[:success] = "Voucher destroyed."
    
    respond_to do |format|
      format.html { redirect_to vouchers_url }
      format.json { head :no_content }
    end
  end

  # To publish voucher 
  def pub_unpub_voucher 
  	
  	uri = URI.parse(request.headers["Referer"])

  	parameters = {:page => 1}
  	parameters[:page] =  CGI.parse(uri.query)['page'].first if uri.query.present?
  	params.merge!(parameters)


  	voucher = Voucher.find(params[:id])
  	voucher.update_attributes(is_active: params[:is_active] ) 	
  	get_vouchers

  	render :partial => 'vouchers'

  end

  private
  def get_vouchers
  	@vouchers = Voucher.order('id').paginate(page: params[:page])  	
  end

end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/vouchers/_form.html.haml
= form_for @voucher do |f|
  - if @voucher.errors.any?
    #error_explanation
      %h2= "#{pluralize(@voucher.errors.count, "error")} prohibited this voucher from being saved:"
      %ul
        - @voucher.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :code
    = f.text_field :code
  .field
    = f.label :valid_days
    = f.number_field :valid_days
  .field
    = f.label :is_active
    = f.check_box :is_active
  .actions
    = f.submit 'Save'

app/views/vouchers/_vouchers.html.haml
%table
  %tr
    %th
    %th Active
    %th Name
    %th Code
    %th Vaild days
    %th
    %th
    %th

  - @vouchers.each do |voucher|
    %tr
      %td= check_box_tag "published_#{voucher.id}", voucher.id, voucher.is_active, :class => "pub_voucher"
      %td= (voucher.is_active) ? "published" : "unpublished"
      %td= voucher.name
      %td= voucher.code
      %td= voucher.valid_days
      %td= link_to 'Show', voucher
      %td= link_to 'Edit', edit_voucher_path(voucher)
      %td= link_to 'Destroy', voucher, :method => :delete, :data => { :confirm => 'Are you sure?' }

:javascript
  $(function() {
    return $(".pub_voucher").on("change", function() {
      var id, publish;
      publish = $(this).is(":checked");
      id = $(this).val();
      return $.ajax({
        type: "POST",
        dataType: "html",
        url: "/vouchers/pub_unpub_voucher",
        data: {
          is_active: publish,
          id: id
        },
        success: function(data) {
          return $("#voucher_content").html(data);
        },
        error: function(object, error) {
          return console.log(error);
        }
      });
    });
  });

app/views/vouchers/edit.html.haml
%h1 Editing voucher

= render 'form'

= link_to 'Show', @voucher
\|
= link_to 'Back', vouchers_path

app/views/vouchers/index.html.haml
%h1 Listing vouchers

- if @vouchers.blank?
  = "No voucher available."
- else
  %div{:id => 'voucher_content'}
    = render "vouchers"

%br
= will_paginate
%br
= link_to 'New Voucher', new_voucher_path

app/views/vouchers/new.html.haml
%h1 New voucher

= render 'form'

= link_to 'Back', vouchers_path

app/views/vouchers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @voucher.name
%p
  %b Code:
  = @voucher.code
%p
  %b Vaild days:
  = @voucher.valid_days
%p
  %b Is active:
  = @voucher.is_active

= link_to 'Edit', edit_voucher_path(@voucher)
\|
= link_to 'Back', vouchers_path